### ISSUE TITLE
This computer no longer recieves updates from Chrome

### ISSUE THREAD

**Issue by dark-passages** [satishsampath/wink-release#26]
After I rendered a video with Wink I clicked on the globe to see my creation.
My browser opened with the video on the screen. It all works great BUT:

![Supported1](https://user-images.githubusercontent.com/53835804/92575680-ed5d2500-f288-11ea-8b03-0af49856ce38.png)

At the top of my browser there is a banner stating "Deze computer ontvangt geen Google Chrome-updates meer. ...."
In English that means "This computer no longer recieves Google Chrome-updates, because windows Vista and Windows XP are no longer supported.", but I'm working on Windows 10. 

I opened the html file from the folder that it was saved in and it works perfectly (no warning message) 
When I open the page from Wink the warning appears, but only if it's the first tab in the browser. 

To repeat this close all your browser instances and click the globe in Wink to show your presentation. 
It looks like Wink is telling Chrome that it's running on a XP or Vista platform and Chrome then shows this message.

**Comment by satishsampath** [comment]
When you see that error message, can you open chrome://version/ in a new tab of the same window and attach that screenshot here?

**Comment by satishsampath** [comment]
I'm not sure if this is related to Wink at all. The html that wink produces isn't really telling the browser to do anything like this.
Could you check if the tips in this reddit thread help fix the issue for you? https://www.reddit.com/r/chrome/comments/43bcp7/this_computer_will_soon_stop_receiving_google/

**Comment by dark-passages** [comment]
It’s not the HTML, If I open the file myself (from my harddrive) Chrome knows i’m working on windows 10 and does not show a message. Only if Wink opens Chrome the message appears. 

Looks like you use XP or Vista to compile Wink and somehow Chrome knows that.

**Comment by satishsampath** [comment]
I use Windows 7 :) which is why this error is something I feel isn't related to Wink.
Anyhow.. i'll keep checking.

**Comment by dark-passages** [comment]
> When you see that error message, can you open chrome://version/ in a new tab of the same window and attach that screenshot here?

When I click on the "View rendered output" button I see the messages in the top of my browser. The about screen shows it realy thinks it's working on windows Vista:

![Windows 6](https://user-images.githubusercontent.com/53835804/92918679-f0464a00-f42f-11ea-93e0-0f72031dae01.png)

When I open the html file from Explorer the message does not appear and behold, chrome knows it's running on windows 10: 

![Windows 10](https://user-images.githubusercontent.com/53835804/92918682-f0dee080-f42f-11ea-89aa-cd362421238e.png)

I marked the texts that are different, but from this I can not see any reason why chrome would think it's running on Vista.

**Comment by satishsampath** [comment]
Here is a test.
1) open File>Preferences
2) delete the url to ffmpeg at the bottom of that dialog
3) click OK
4) select Project>Render
You should see a dialog asking you whether you want to install ffmpeg and view instructions. Click "Show ffmpeg install instructions"

If that opens properly in chrome without the above-mentioned error, then I think I can fix the problem.

**Comment by dark-passages** [comment]
Any link opened from Wink shows the message if the browser is not opened yet. 
If the browser is already open and the link is opened in a new tab the message does not appear.

![Supported3](https://user-images.githubusercontent.com/53835804/93125482-7e8a2c80-f6cb-11ea-9f92-eab926459903.png)

**Comment by dark-passages** [comment]
Just curious: why are you still working with ffmpeg? The ffmpeg website states it’s no longer supported. Also strange is the dialog that keeps popping up every time if i click render and I don’t want to install the unsupported codec

**Comment by satishsampath** [comment]
FFmpeg is well supported, just that one person decided to stop creating builds. Another reliable mirror has been found - https://ottverse.com/ffmpeg-builds/ . I'm waiting for them to put up release builds before linking to them. FFmpeg also gives you smaller .mp4 file sizes if used with Wink, so that you don't have to pay too much to host these videos.

Regarding the chrome error, can you go to the Chrome.exe directory, right click on the .exe file and select the Compatibility tab? Please verify if the "Compatibility mode" checkbox is enabled in there or not. I've shown an example here. It should be unchecked normally.
![Capture](https://user-images.githubusercontent.com/2305978/93157421-0c134f80-f6bf-11ea-9885-c3c95bffd865.PNG)

**Comment by satishsampath** [comment]
@dark-passages any luck with the above steps?

**Comment by dark-passages** [comment]
I can try the above suggestion for research purposes, but I fail to see how this is a solution, do you want to include “Before using wink, make sure chrome is in compatibility mode.” in the manual?

Just to make sure you know:
* I have no problem using the FFMPEG codec, I just wanted to make sure it is well maintained or you will get a lot of similar questions from other users. My suggestion is to link to a website that does not show a warning message or link to your own website.
* I have no problem with the message that Chrome shows me, I know I have the latest updates. Again, other users will ask you similar questions if this is not fixed (or explained in the manual).

**Comment by satishsampath** [comment]
Re: ffmpeg, I've already updated the link in the Wink website to point to
the new URL which doesn't show the warning. So it's all good.
Re: Chrome, yes.. I'd like to check if it's the compatibility setting
that's giving you that warning. I haven't seen that warning in any other
computer, so want to check if it's your machine's Chrome setting or not.

**Comment by dark-passages** [comment]
> Regarding the chrome error, can you go to the Chrome.exe directory, right click on the .exe file and select the Compatibility tab? Please verify if the "Compatibility mode" checkbox is enabled in there or not. I've shown an example here. It should be unchecked normally.

Not sure what you would like me to do here, it was unchecked and the warning messages only appears when I open Chrome from Wink, if I check it and select Vista SP2 the warning message always appears (Also when I start Chrome without the use of Wink). So I unchecked the box again meaning the warning only appears when I open Chrome from Wink.

**Comment by satishsampath** [comment]
Ok thanks, that helps. I'm still figuring out what's going on.

**Comment by dark-passages** [comment]
Wink now opens Chrome without the warning message! 
Congratulations you did it! 
Can i ask what was wrong?

**Comment by satishsampath** [comment]
Glad to hear that it works fine now. I don't think I did anything here though :)

**Comment by dark-passages** [comment]
I did notice a big update in Chrome (news section in the F12 screen) could be they fixed it.

Groetjes,
Arjan

On 25 Nov 2020, at 17:17, Satish Sampath <notifications@github.com> wrote:

﻿

Glad to hear that it works fine now. I don't think I did anything here though :)
