### ISSUE TITLE
Continued Input-Driven Capture keyboard issues.

### ISSUE THREAD

**Issue by t-rains** [satishsampath/wink-release#31]
**This issue was closed as #28.** 

I am still unable to get keyboard triggering to work. I have added a screenshot of another attempt to capture the making of a test Word 2013 document, including the formatting and ribbon change to add a symbol (the solid circle). Closing out the session there were no captured frames. 'Mouse Click', 'Key Press', and 'Use Timed Capture When Mouse Button Is Down' were all checked in the "New Project Wizard - Step 1 of 2" dialog. Timed Capture and Manual Snapshot Capture work well and mouse movement is captured in both of those capture modes. Only Input-Driven Capture is not working.

**Comment by t-rains** [comment]
Here is a screenshot of that last attempt

![Input-Driven Capture end screen](https://user-images.githubusercontent.com/70729692/92974146-6ea7e980-f43a-11ea-93a4-776e59112a75.png)

**Comment by satishsampath** [comment]
Can you try with another application, like Notepad? 

Also, when you press 'Alt + Pause', the Wink icon in the right/bottom system notification area should turn into a slightly different icon (with a mouse pointer picture on top of the Wink logo). Do you see that happen? Please send a screenshot of your full screen after you press "Alt + Pause" to show what's happening

**Comment by satishsampath** [comment]
@t-rains any thoughts on my question above?

**Comment by t-rains** [comment]
I have tested Wink in a number of applications and so far:
- Input-Driven capture works as expected in Chrome, GIMP, Malwarebytes, Notepad, PDF Exchange Editor, Sweet Home 3D.
- Only mouse clicks and mouse movement works in HP OfficeJet Pro 8710 PCL-3 (Network): HP Printer Assist.
- It does not work in Evernote, Excel 2013, Help N Doc, Mendeley, Word 2013.
- My system locks up trying to record File Explorer, the Windows Desktop.

**Comment by satishsampath** [comment]
I'll continue to test these, but my current plan is to release with these known issues.

**Comment by t-rains** [comment]
UPDATE: I have substantially updated my hardware, still using Windows 10 Home 64 bit. I am now using Microsoft 365 instead of Office 2013, otherwise, all tested programs from the 9/14/2020 comment work as well without a problem.
