### ISSUE TITLE
Unable to render Tutorial 1

### ISSUE THREAD

**Issue by t-rains** [satishsampath/wink-release#38]
I get the error message "Unable to load control bar C:\Program Files\DebugMode\Wink\FlashControlBars\rounded_green.wfc". I have looked and the folder and files are in that location. Relabeling a different control bar that I know renders did not help and the rounded green control bar works with new Winks.

**Comment by satishsampath** [comment]
Ah, thanks. Looks like the project needs to be updated to the new controlbars location. I'll fix it.

**Comment by satishsampath** [comment]
Fixed in the public release build.
