### ISSUE TITLE
Feature Request: PDF layouts

### ISSUE THREAD

**Issue by t-rains** [satishsampath/wink-release#39]
Is it possible to allow more than one frame shot per sheet, to change the size of the shots to allow annotation, or to not to clip the sides when using Portrait layout?

**Comment by satishsampath** [comment]
It'll help if you can attach images showing what you are suggesting here, perhaps two images with one showing how it saves PDFs today and one showing how you want it to save.

**Comment by t-rains** [comment]
I have included an example of a '2 frames per sheet' PDF mock-up. This is for printing the PDF.

The other 2 images are a landscape and portrait layout of the same Wink PDFs 
[2 Frames per Sheet PDF example.pdf](https://github.com/satishsampath/wink-release/files/5289194/2.Frames.per.Sheet.PDF.example.pdf)
![PDF Landscape ](https://user-images.githubusercontent.com/70729692/94377460-a10e4380-00d6-11eb-8c54-936bbca3aa2b.png)
![PDF Portrait](https://user-images.githubusercontent.com/70729692/94377465-a8cde800-00d6-11eb-9c5c-dfb023052b94.png)


where you can see the sides are chopped off in portrait layout.

**Comment by satishsampath** [comment]
I tested this a bit and it's possible to do what you ask by following these steps:
- Export as PDF, with the "Fit Page to Image". This creates a PDF where each image is on one page and the page size matches the image dimensions
- Open the PDF in any PDF viewer (I opened in Chrome).
- Print, and select "Pages per sheet" as 2 or 4 as you need them

Given that this can be done already, I'd like to keep Wink simple and export to PDF with no new features. Closing this issue as a result.

**Comment by t-rains** [comment]
Thanks, Satish for checking on that. I should have done that first. I agree to keep Wink as simple as possible doing what it does best.
