### ISSUE TITLE
[v3] quality rendering

### ISSUE THREAD

**Issue by SebCanet** [satishsampath/wink-release#42]
Many thanks for your work! In France, a lot of teachers used Wink to create tutorials for students, and I'm very happy to use again my wnk files, and update them. But before updating, I have a rendering quality problem with v3 and old wnk files.
With same wnk, when I create an exe file I have a good result:
![wnk_exe](https://user-images.githubusercontent.com/6362199/94465339-0be77980-01c0-11eb-8e76-77fe677bc113.jpg)

But with new MP4 in v3 I obtain this (at the same timing):
![wnk_mp4](https://user-images.githubusercontent.com/6362199/94465354-10ac2d80-01c0-11eb-93e3-dd0bcff1da25.jpg)

And the v3 html read by Firefox (at the same timing):
![wnk_firefox](https://user-images.githubusercontent.com/6362199/94465359-143fb480-01c0-11eb-9ceb-3a322d07f08c.jpg)

Can you help? Thanks a lot!

**Comment by satishsampath** [comment]
Have you tried opening "Project > Settings" dialog and giving a higher value for the "video bitrate" field? Looks like the default value that Wink calculates may not be sufficient for your video.

**Comment by SebCanet** [comment]
Even with doubled bitrate (600 000) I still have quality issue:

![Image 1](https://user-images.githubusercontent.com/6362199/94523206-24dc4300-0231-11eb-907c-47db57982f85.png)

**Comment by satishsampath** [comment]
Can you share the .wnk project with me in this issue? I'll take a look.

**Comment by SebCanet** [comment]
Yes, no problem, thanks to have a look on it.
Download link: [http://dl.free.fr/w8E4oHGtv](http://dl.free.fr/w8E4oHGtv)

**Comment by satishsampath** [comment]
Thanks. I was able to get good rendering quality by setting "video bitrate" to 900000 and "frame rate" to 10. Can you please check if those work for you?

**Comment by satishsampath** [comment]
I've made code changes to set a better default bitrate for new projects & Wink 2.0 projects that are opened by Wink 3.0. Fix should be ready in the next release.

**Comment by SebCanet** [comment]
Thanks for testing, but even with this settings the v3 version has not the same quality as the v2 one. Sometimes it's good, sometimes it's blurs.
Example took at the same moment:
![Image 001](https://user-images.githubusercontent.com/6362199/95047705-d3c3c780-06e6-11eb-98c8-f08b4326f8e8.png)
![Image 002](https://user-images.githubusercontent.com/6362199/95047708-d45c5e00-06e6-11eb-8038-bb7b7404ac06.png)

**Comment by satishsampath** [comment]
Were these videos rendered for the same framerate and videobitrate values?

If yes, please enter 1049088 as the value for video bitrate and 10 as the value for frame rate. Let me know if that works better consistently.

**Comment by SebCanet** [comment]
The one down, clear one, is EXE from v2 ; the upper one with blurs is the video created with v3 and settings you told me to use.

The picture below is v3 with last settings (and file is now size double of the exe v2 version):
![rheologie mp4_snapshot_01 27_ 2020 10 05_17 05 17](https://user-images.githubusercontent.com/6362199/95096783-01336400-072d-11eb-967a-5c46e621ccee.jpg)

**Comment by satishsampath** [comment]
@SebCanet is there an email I can reach you directly at? I'd like to send you a test build to see if that fixes the issue.

**Comment by SebCanet** [comment]
It's not in my profile? Here it is: scanet@libreduc.cc

Many thanks!

**Comment by satishsampath** [comment]
Thanks, I shared a build via Google Drive and you should get an email about it.
Can you open your old Wink 2.0 .wnk file using this build, leave videoBitrate to whatever was set automatically, and render? See if that creates a better mpeg4 file. If it is still poor, please share with me the full .mp4 file so I can look.

**Comment by SebCanet** [comment]
Dammit, it's still poor. There it is: [http://dl.free.fr/oExtSY0RI](http://dl.free.fr/oExtSY0RI)

**Comment by satishsampath** [comment]
Can you tell me what value you see for videoBitrate when you go to the
Project > Settings dialog

**Comment by satishsampath** [comment]
Also, which windows version are you on?

**Comment by satishsampath** [comment]
Do you have ffmpeg installed/used by Wink?

**Comment by SebCanet** [comment]
I did like you asked : "leave videoBitrate to whatever was set automatically".
I use Windows 7x64 or Windows10, and ffmpeg-4.3.1-2020-09-21-full_build

**Comment by satishsampath** [comment]
> I did like you asked : "leave videoBitrate to whatever was set
automatically".

That's good. Can you still open Project Settings dialog and tell me what
value it had selected automatically for video bitrate?

**Comment by SebCanet** [comment]
Ok, sorry, so:
bitrate: 300000
audio: 10000
frame: 20

**Comment by satishsampath** [comment]
That looks like what was set earlier. Can you increase the frame rate
spinner one value up and then down, which will recalculate the video bit
rate? Then render again

**Comment by SebCanet** [comment]
Which value do you exactly want me to try?

**Comment by satishsampath** [comment]
Just click the up arrow next to frame rate, then down arrow, and you'll see
a new value in the video bitrate field. Then close by clicking the Ok
button and render

**Comment by SebCanet** [comment]
The value is 2098176. It works! May thanks!

**Comment by satishsampath** [comment]
Great! If the quality of the output is good now, can you please close this
issue?

**Comment by SebCanet** [comment]
Perfect!
