### ISSUE TITLE
Cursor rendering and dialog

### ISSUE THREAD

**Issue by dark-passages** [satishsampath/wink-release#43]
The buttons on the Cursor dialog overlap the image of the cursor:

![Cursor1](https://user-images.githubusercontent.com/53835804/94557575-0c831d00-025f-11eb-87de-3f0bfae4bcae.png)
![Cursor2](https://user-images.githubusercontent.com/53835804/94557577-0d1bb380-025f-11eb-8b7b-dc93609a41d4.png)

The black background on the cursor is usefull while editing the presentation (clear to see the difference between my cursor and the one from Wink) but it seems that the black background is also used in the final rendering. I noticed many usefull cursor images in the program folder, but there is no normal (like the screenshot but without the black) cursor there. Would also be nice if the available cursors are listed in the program, without me having to import them one-by-one.

**Comment by satishsampath** [comment]
Can you tell what OS version you have running and what display settings you have?

**Comment by satishsampath** [comment]
I was able to fix the alignment of the preview i.e. move the buttons below the cursor image. Now trying to figure out why you are seeing black background for the cursor. If you can tell me the OS version and what display settings you have, that'll help.

**Comment by dark-passages** [comment]
![Windows 10](https://user-images.githubusercontent.com/53835804/95141096-93a92700-0770-11eb-98a9-d62433537dfd.png)
![Display](https://user-images.githubusercontent.com/53835804/95141318-1df18b00-0771-11eb-8e28-208203741246.png)
I hope this is enough info, if not let me know what else you like to know.

P.S. I used to have the display setting to scale to 125% so I could read the text better, but Wink 2.0 could not make sence of that. Will try to go back to 125% again and test that with Wink 3.0 at a later date.

**Comment by satishsampath** [comment]
Can I get your email ID, to share a custom build of Wink 3.0? I'd like to test on your machine and see if it gets this issue fixed.

**Comment by satishsampath** [comment]
Oh, and do you have any software installed to give additional cursors in windows, or is it a regular windows install?

**Comment by dark-passages** [comment]
Just plain windows 10 on my office laptop, nothing fancy about it.

**Comment by dark-passages** [comment]
My email is arjan.de.haas@gmail.com

**Comment by satishsampath** [comment]
Thank you. I have shared a custom build with you via Google Drive. Could you please install it, run once, open any Wink project, click on a cursor and open the cursor dialog? Once you do this, you'll see a file named "winkcursors.bin" in your "My Documents" directory. Please send that file by attaching it to this github issue and I'll take a look.

**Comment by satishsampath** [comment]
@dark-passages  any chance you were able to test?

**Comment by satishsampath** [comment]
Fixed in v3.01
