### ISSUE TITLE
National characters not showing properly

### ISSUE THREAD

**Issue by RobertSeles** [satishsampath/wink-release#44]
Hi Satish,
when I opened a project originally created in version 2.0, there were unreadable some of the national characters in the textboxes. For example: Slovak ľ was shown (and generated) as ¾
Regards,
Robert
[Introduction to Archimate & PSS Metamodel.zip](https://github.com/satishsampath/wink-release/files/5326593/Introduction.to.Archimate.PSS.Metamodel.zip)

**Comment by RobertSeles** [comment]
There is one more unpleasent behavior very likely connected with national environment.
When I enter a text box (F2), size of the box changes after the change, see the screenshots.
![step4](https://user-images.githubusercontent.com/50650460/95555059-8199e380-0a11-11eb-9631-7315dad90db0.png)
![step1](https://user-images.githubusercontent.com/50650460/95555061-82327a00-0a11-11eb-8964-b03537c5c397.png)
![step2](https://user-images.githubusercontent.com/50650460/95555063-82cb1080-0a11-11eb-8852-5edc44e3e571.png)
![step3](https://user-images.githubusercontent.com/50650460/95555065-8363a700-0a11-11eb-9821-6af9581e7036.png)

**Comment by RobertSeles** [comment]
One more unpleasent behaviour probably connected with the national environment.
When I enter a text box and change the font to Arial, size of the text box goes bigger.
![step1](https://user-images.githubusercontent.com/50650460/95555437-17357300-0a12-11eb-9f23-b826052b2da6.png)
![step2](https://user-images.githubusercontent.com/50650460/95555446-1a306380-0a12-11eb-8a99-96ef608d2ff3.png)
![step3](https://user-images.githubusercontent.com/50650460/95555458-1c92bd80-0a12-11eb-888b-727eac2d1038.png)
![step4](https://user-images.githubusercontent.com/50650460/95555462-1e5c8100-0a12-11eb-83de-73111d893ac6.png)

**Comment by RobertSeles** [comment]
Another unpleasent behaviour most likely connected with the national envirmńment.
Editing a text box (F2) changes size of the box.
![step1](https://user-images.githubusercontent.com/50650460/95557105-9deb4f80-0a14-11eb-8221-864133741850.png)
![step2](https://user-images.githubusercontent.com/50650460/95557113-9fb51300-0a14-11eb-8998-316c4793c951.png)
![step3](https://user-images.githubusercontent.com/50650460/95557127-a2b00380-0a14-11eb-973f-d78a20644445.png)
![step4](https://user-images.githubusercontent.com/50650460/95557132-a5125d80-0a14-11eb-90ce-d5709881ab33.png)

**Comment by satishsampath** [comment]
I looked at the .wnk file, and the specific character "¾" is showing up because the file actually has the unicode value 0xBE in that part of the string (which is equivalent to the character ¾). If I replace that with the Slovak ľ , that saves to the file properly with the unicode value 0x13E.
Can you please do the same, i.e. replace it with the correct character, save it and open again to verify?

**Comment by satishsampath** [comment]
@RobertSeles any chance you were able to check what I mentioned above? If it doesn't happen, we can close this issue.

**Comment by RobertSeles** [comment]
Hi Satish, in the meantime I have retyped all broken characters in Wink 3.0, you can close the issue.
