### ISSUE TITLE
Documentation findings

### ISSUE THREAD

**Issue by t-rains** [satishsampath/wink-release#45]
In looking over the Tutorials and User Manual, I have noticed some things that you may want to update when time allows. These are more of an issue for new users.

In Tutorial 1:

- Frames #104-5 and 111-13 show Flash in the old dialogs instead of video.

In the User Manual:

- There is no current Table of Contents but it is referenced on p.14 and space is left in the page numbering for it.
- Feature Request: If adding a Table of Contents, can you make the references links (also the in-text references).
- There is no Section 3.4 (Palette) now but the Section numbering shifts from 3.3 to 3.5. However, Section 3.10.2 (Control Bars) was shifted to 3.10.1 on p.29. If you do shift Section 3.5 number to 3.4, there are references to change on p.14.
- You may want to expand on the enhanced role of Section 3.5.2 (Stay in this frame for time)
- The PlayOverlay 'button' to start Winks in a browser is not discussed.
- Consider adding the recommendation to capture even number dimensioned windows for mp4 output in Section 2.2 'Step #1' (p.7) and/or Section 3.2.1 'Step #1' (p.11).
- The 4 Shortcut keys about frames before the last one in the table on p. 31 are missing the last symbol in my manual.

**Comment by satishsampath** [comment]
Thanks, I'll take a look.

**Comment by satishsampath** [comment]
Fixed in v3.01

**Comment by t-rains** [comment]
I hope this is not too late for the update. I was testing the keyboard shortcuts and noticed that both the "3.11 Shortcut Keys" table on p. 30 and the "3012 Toolbar" on p. 31 references the **pallette**.

**Comment by satishsampath** [comment]
Good catch. I've removed them and they'll not be present in the next release.
