### ISSUE TITLE
Sound Editor Crashes trying to edit track

### ISSUE THREAD

**Issue by t-rains** [satishsampath/wink-release#46]
Wink crashes when I try to trim an audio track. I can import it into the Wink OK despite the 11025 Hz warning message even though I am using a 11025 Hz .wav file. It also crashes trying to edit .mp3 files.

**Comment by satishsampath** [comment]
I think I found/fixed the issue. But to test it properly, can you give me exact step by step instructions? Please give for both the trim scenario and the editing mp3 scenario.

**Comment by t-rains** [comment]
Here are the steps I attempted to trim and edit (both stop at the same common points) while in an open Wink project.

1. Click on the 'Add Sound' icon.
2. Click on the 'Open File' icon.
3. Open a file. Some files with crash Wink here with the 'Wink Exception' error message.
![Crash at open file exception error](https://user-images.githubusercontent.com/70729692/96792151-a5184300-13ae-11eb-8d48-87ad3b28ffad.png)

4. Click OK for the 11025 Hz sample rate warning message.
5. Click inside the waveform display to produce the red line.
6. Drag the red line to produce a white selected area. At this point, I often get the 'wxWidgets Debug Alert'. If I select "Continue", I can continue to edit and even add the sound to the frame. I would have to keep pressing "Continue" every time I attempt to edit the file. If I select "Stop" then Wink crashes.
![Crash at open file exception error](https://user-images.githubusercontent.com/70729692/96792258-e3adfd80-13ae-11eb-8340-fabefd3bd25d.png)

7. If I get this far, I do not have any further problems with the Audio Editor during that session of the editor.

The audio crashes are not consistent. They occur more often with .wav files than with .mp4 files, with sizes from 2KB (0.10 seconds) sound files to 9.529 Meg (479.08 seconds) music files. 

I have not found any consistent pattern yet when it will occur. Some files will even crash during one Wink session and not on another while other files are consistent in the behavior. Playing the track before editing does not make any difference. The Wink exception occurs less often than the wxWidgets Alert. The most vulnerable times appear to be when the first audio file is opened but that I have not confirmed yet.

**Comment by satishsampath** [comment]
Any chance you can attach to this issue one of the files that consistently crashes Wink?

**Comment by t-rains** [comment]
I have uploaded 3 audio files to our Google Drive folder in the sub-folder "Audio Crash Files". There are 2 sound files, a .wav, and a .mp3 that throw the wxWidgets Debug Alert. I also included a .mp3 music file that throws the Wink exception. Files sizes here range from 2KB to 1,900 KB.

**Comment by satishsampath** [comment]
Thanks! This helped. I have shared a custom build of Wink with you that has the fix. You should get an email from Google Drive with a link to download it.
Can you please install that and give it a try?

**Comment by t-rains** [comment]
The files I uploaded previously edit without any problem and so do most others. I no longer get the Wink exception and wxWidgets Alert messages. 

Now, however, many files have other issues. Almost all so far are with .wav files. I have uploaded examples of each issue to the Google Drive folder.

- These files only play static in the Wink audio editor, they play fine elsewhere: 395492, 327687, 328824
- These files crash after an "Unable to Load" message: 393064, 497715, 400695
- These files simply crash Wink with no message: 355336, 5333946, 463214.

**Comment by satishsampath** [comment]
@t-rains Thank you so much for all the test files. I was able to find and fix many issues and now every single one of them are opening/working properly.
Can you download the test build again, from the exact same link I sent earlier, to test with these audio files? It should all work as expected.

**Comment by t-rains** [comment]
Thank you, Satish! This is much improved. All files play and edit without a problem (tested in ~ 80 files). All files load faster with better fidelity in the editor as well.

**Comment by satishsampath** [comment]
Fixed in v3.01
