### ISSUE TITLE
Feature Request: Quantitative cursor smoothness adjustment

### ISSUE THREAD

**Issue by t-rains** [satishsampath/wink-release#47]
Feature Request: A quantitative indication of the cursor movement 'Smoothness Slider' setting to more easily return to a previous value or to estimate a new one. It appears that a "meter" of sorts is there in the middle of the header row for smoothness [ (0) ] but it does not change from 0 with a smoothness change.

**Comment by satishsampath** [comment]
I managed to get the "meter" part that shows [ (0) ] working properly.

**Comment by satishsampath** [comment]
Fixed in v3.01
