### ISSUE TITLE
Unable to embed audio into more than one frame at a time

### ISSUE THREAD

**Issue by t-rains** [satishsampath/wink-release#50]
Images, shapes, callouts, and buttons can all be put into more than one frame at a time using 'Control + C' or 'Shift' key combinations. But when I try to put the same audio track into multiple frames at a time, such as for a bouncing sound, only the last selected frame gets the audio despite all the frames being selected.

**Comment by satishsampath** [comment]
Interesting. Is there a genuine need for this feature i.e. why would you want to have the same audio repeat across many frames?

**Comment by t-rains** [comment]
You are right, audio cues tend to be unique most of the time. I have used the same cues for things like correct or incorrect answers in quizzes, to announce tips, to sound out checkmarks, etc. however these are not common events. I only mentioned that since it was a break in the operational pattern for the rest of the inclusions (images, shapes, callouts, buttons).
