### ISSUE TITLE
Audio Editor tracking accuracy

### ISSUE THREAD

**Issue by t-rains** [satishsampath/wink-release#51]
I notice that when I play an audio track, the traveling red line and 'Position' marker gets progressively farther behind the track. This makes editing the end of the track significantly more challenging. If you stop the track, the sound resets to the position of the red line and 'Position' marker which helps but is still cumbersome. An easy file to see this on is the 5333946 audio file in the Google Drive "Audio Crash Files" folder.

**Comment by satishsampath** [comment]
Great find, you are really good in finding these issues :)

**Comment by satishsampath** [comment]
Fixed in v3.01
