### ISSUE TITLE
Next Frame Buttons On Some Frames Do Not Work

### ISSUE THREAD

**Issue by LarryKu** [satishsampath/wink-release#56]
I have started converting older Wink tutorials to the new MP4 format (fantastic enhancement). What I have discovered is that some "Next Frame" buttons do not work. You can click forever, and it will never proceed to the next frame. Many work flawlessly, but not all of them. My work-around is to replace the "Next Frame" buttons with "Go To Frame" buttons pointing to the next frame. All "Prev Frame" buttons work flawlessly.

I can provide the Wink source file if that would be helpful.

**Comment by LarryKu** [comment]
I created one tutorial first) using the "Next Frame" buttons; second) replacing "Next Frame" buttons with "Go To Frame" buttons. When I compared the corresponding javascript files, I noticed the target frame for the "Go To Frame" buttons were always 5 frames from the current, while the "Next Frame" buttons were always one frame more.

The tutorial with "Go To Frame" buttons work flawlessly, while the "Next Frame" button tutorial has many buttons that do not work. Attached is a comparison of the first four frames of the Javascript files with the button variables highlighted.

[Wink_NextFrame.pdf](https://github.com/satishsampath/wink-release/files/5662067/Wink_NextFrame.pdf)

**Comment by satishsampath** [comment]
>  I noticed the target frame for the "Go To Frame" buttons were always 6 frames from the current, while the "Next Frame" buttons were always one frame more.

That's a great observation and the exact fix I need to make. Thank you.

**Comment by satishsampath** [comment]
> I can provide the Wink source file if that would be helpful.

Can you please provide a sample file? That will help me test before and after the fix.

**Comment by satishsampath** [comment]
Fix will be available in the next public release.
